### PR TITLE
wip - Add support for generating custom Remove methods for repeating …

### PR DESCRIPTION
**Pull request by nkm8**
…fields

These changes are dependent on https://github.com/duaneedwards/nHapi/pull/75 and cannot be merged until the nHapi PR is merged and a new version is available in NuGet.  After that happens, I can update this PR to bump the nHapi version and remove the local file reference to nHapi.Base.dll.

Currently, I only updated the reference in the v23 project to ensure the tests complete successfully.  If you want to build/test locally, you will need to temporarily unload the other projects.

### CODE REVIEW

**Comment by dib0** [comment]
Thanks! Let's wait on #75 in nHapi before integrating this.

**Comment by nkm8** [comment]
Looks like there is finally some motion on https://github.com/nHapiNET/nHapi/pull/75
I pulled from master and resolved the merge conflicts - I don't use nHapi anymore, so I can't easily build/test this.

**Comment by milkshakeuk** [comment]
@dib0 Hi, the changes to **nHapi** are in master but not in a release version yet, I'm hoping to create a new Preview Release soon with @nkm8 changes in.

In Theory you could create a preview version of **NHapiTools** that generates source code from the preview release of **nHapi** once it's been created/released.

**Comment by milkshakeuk** [comment]
@dib0 the changes are in v3.0.0-preview.2 and of course v3.0.0-preview3, I'll let you know when v3 final is releeased.

**Comment by milkshakeuk** [comment]
@dib0 nHapi v3 has been [released](https://www.nuget.org/packages/nhapi/) and #21 should enable this PR to generate the extra extensions.

**Pull request merged**
