### PR TITLE
Add support for nHapi 3.0.0

### PR DESCRIPTION
**Pull request by milkshakeuk**
- add additional GitHub Action Workflows (post test results for PRs)
- replace xunit with nunit (xunit hasnt been updated in a long time and was causing issues)
- update dotnet SDK to 5.0.301 (Source Generator now targets net5.0)
- remove unused references and using statements
- only sign dlls with strong name with building with Release config

### CODE REVIEW

**Comment by milkshakeuk** [comment]
@dib0 hi, are you around?

**Comment by dib0** [comment]
Hi! Yeah, I'm keeping up to date with comments, but haven't gotten around to looking into it yet. Sorry for that...

I have merged the pull request will test and look into it later on

**Comment by milkshakeuk** [comment]
@dib0 Hey, have you had chance to look at this yet? I know a lot of people will put of upgrading to nHapi v3 since they use it in conjunction with NHapiTools.

**Comment by milkshakeuk** [comment]
@dib0 Hey, any updates on this?

**Comment by dib0** [comment]
Hi,

sorry. Didn't have the time to look into it yet. Busy keeping two companies running.

**Comment by milkshakeuk** [comment]
Hi @dib0,
Sure, hopefully you will get chance soon.

**Comment by milkshakeuk** [comment]
@dib0 sorry to be a pain, just checking in on this one... any news?

**Comment by dib0** [comment]
Hi,

On vacation right now. Have some time in the mornings, so working on it. It was a while ago... It seems I just have to test it and release it, right?

**Comment by dib0** [comment]
And sorry it is taking me this long...

**Comment by milkshakeuk** [comment]
@dib0 no need to apologise, life doesn't always present lots of spare time and opportunity for open source contributions.

Testing it sounds sensible to me, and maybe have a think about the version number before releasing.

Don't forget to create a matching release in GitHub (I think its currently behind nuget.org).

**Comment by dib0** [comment]
Ok, I've solved some extra issues,tested etc. Bumped version to 2.0 and released through github and nuget. Any issues or things I missed, please let me know!

**Comment by milkshakeuk** [comment]
@dib0 okay thanks, I looked at your changes and left a comment.

**Pull request merged**
