### PR TITLE
re-sturcture the solution and test gitgub actions.

### PR DESCRIPTION
**Pull request by milkshakeuk**
@dib0 I have spent a bit of time on this and it would be good if you could have a look though, if you have any questions let me know.

I have done the following.

* restructured the project to a more modern style
* converted TestApp to unit tests
* split out code generation to a new console app
* added basic github CI/CD build/test/pack actions

### CODE REVIEW

**Comment by milkshakeuk** [comment]
Hi @dib0, have I had any chance to review this pr yet?

**Comment by dib0** [comment]
Hi, sorry, not yet. It has been e busy few weeks. It's still on my todo-list, so I won't forget. I hope I can make time for it this weekend.

**Comment by milkshakeuk** [comment]
@dib0 ok thanks a lot

**Review by dib0 — APPROVED** [review]
Nice work. Beautiful step towards a modern setup of the project

**Pull request merged**
