### PR TITLE
preperation for netstandard2.0 support

### PR DESCRIPTION
**Pull request by milkshakeuk**
@dib0 this commit puts everything in place to make NHapiTools ready for `netstandard2.0`+ beyond support.

When you build this project with `dotnet build -c Release` this will build against all target frameworks i.e. `net45` and `netstandard2.0`.
When restoring nuget packages against the `netstandard2.0` it will give warnings about `nhapi` itself which currently doesn't support `netstandard2.0` however a while ago I did create a [pull request](https://github.com/duaneedwards/nHapi/pull/112) for that.

I don't suppose you have any way of contacting @duaneedwards as he has gone radio silent for a few years and he hasn't left any direct methods of contact.

### CODE REVIEW

**Comment by milkshakeuk** [comment]
@dib0 to build the first time you may need to delete the `bin` and `obj` folders first.

If you want the build to just target `net45` you would just run the following command.

```
dotnet build -f net45 -c Release
```

You can just use visual studio but you will need a version of the dotnet core SDK installed to use the `dotnet cli` just get the latest one from [dot.net](https://dot.net).

**Comment by dib0** [comment]
Thanks. I hope I can take a look at your pull request later today, but it might be next week before I have the time. Sorry for the delay

**Comment by milkshakeuk** [comment]
@dib0 thanks for the response it's good to know u are still active, hopefully @duaneedwards will also respond one day and we can finally use nhapi with more modern versions of dotnet

**Comment by dib0** [comment]
Alright. Thanks man. Building works fine. I see you've also updated the NuGet package :-) Thanks! I've updated the nuget package

**Comment by milkshakeuk** [comment]
@dib0 I don't suppose u have anyway of contacting @duaneedwards?

**Comment by dib0** [comment]
Sadly, not any other ways than you have. Of course, we can consider just to revive NHapi, create a new repo and support it from there on.

**Comment by milkshakeuk** [comment]
@dib0 I'm more than happy to help with that, the only issue here is obtaining a copy of the hl7 access database `hl7db.mdb` from hl7.org without paying for it.

**Comment by dib0** [comment]
I'll reach out to the HL7 organization and see if some arrangement is possible.

**Comment by milkshakeuk** [comment]
@dib0 ok thanks, let me know how it goes.

**Comment by duaneedwards** [comment]
Hi guys,

Sorry for the late reply, moving house and still don't have internet
connection yet, but hopefully will in the coming week or so.

I'm thinking to setup nhapi as a GitHub organisation, would you like to be
a part of that Jake?

Don't know how to manage the NuGet publishing side of things as an org off
the top of my head but I'm sure it's simple enough.

I'm thinking that'd be a better transition then a hard fork.

At any rate should be a bit more responsive soon,

Duane

**Comment by milkshakeuk** [comment]
@duaneedwards sure, sounds good, can't promise I can dedicate lots of time with work and family, but I'll do what I can towards helping update nhapi for usage with netstandard2.0 and above so modern dotnet applications can utilise nhapi.

**Comment by dib0** [comment]
Hi @duaneedwards,

Hope everything is going well with moving :-) Agree that a hard fork wouldn't be ideal.

If there is anything I can do to help, please let me know!

**Comment by milkshakeuk** [comment]
@duaneedwards hope your house moving is going well, just wanted to check if you've had the chance to look into GitHub organisations, not to worry if not I realise moving house is a busy time.

**Pull request merged**
