### PR TITLE
Upgrade nHapi to latest version; add extension methods for new HL7 ve…

### PR DESCRIPTION
**Pull request by nkm8**
…rsions; switch to dynamic generation based on nHapi package version

### CODE REVIEW

**Comment by dib0** [comment]
Thanks!

**Comment by nkm8** [comment]
@dib0 Happy to help. I'm not sure what your release process is, but it would be great to tag a new release for nuget: https://www.nuget.org/packages/NHapiTools/

Great job! These tools are extremely helpful.

**Comment by dib0** [comment]
:-) Thank you!

I'll see if I can create a new release. It will probably be Tuesday before I can manage.

**Comment by dib0** [comment]
Hi!

I just created the 1.7 release and uploaded it to NuGet.

**Comment by nkm8** [comment]
Looks great - thanks!

**Pull request merged**
