### PR TITLE
Added snk to projects

### PR DESCRIPTION
**Pull request by martintro**
We use snk to sign our internal projects and then we cannot use your nuget package because the DLLs are not signed.

### CODE REVIEW

**Comment by dib0** [comment]
Thanks!

I'll add it to the next release.

**Comment by martintro** [comment]
I appreciate quick response, thanks! When do you think next release will be?

**Comment by dib0** [comment]
I'm not sure. I'll try to get to it this weekend.

**Comment by martintro** [comment]
Perfect :)

**Comment by dib0** [comment]
Ok, just uploaded V1.9 including NuSpec packages.

Thanks!

**Comment by martintro** [comment]
Great, thanks again! :)

**Pull request merged**
